config/routes.rb
WebcollectorApp::Application.routes.draw do
  devise_for :users do
    get '/' => 'devise/sessions#new'
  end
  resources :folders
  resources :user
end

app/models/folder.rb
class Folder < ActiveRecord::Base
  attr_accessible :name, :content, :notes
  
  # Folders belong to a user
  belongs_to :user
  
  # Validations
  validates :content, :presence => true
  validates :name, :presence => true
  validates :user_id, :presence => true
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible  :name, :email, :company, :occupation, :location,
                    :password, :password_confirmation, :remember_me
  
  # Users have many folders that are associated with each user
  has_many :folders, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  
  private
  
  # Overwriting the sign_out redirect path method
  def after_sign_out_path_for(resource_or_scope)
    '/'
  end
  
  # Overwriting the sign_in redirect path method
  def after_sign_in_path_for(resource_or_scope)
    '/user'
  end
end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController
    before_filter :authenticate_user!

    # The new action takes in new folder data from the form in the view
    def new
      @user = current_user
      @folder = Folder.new
    end

    # The create action creates a new folder through the current user
    def create
      @folder = current_user.folders.build(params[:folder])
      if @folder.save
        flash[:notice] = "Folder Created!"
        redirect_to "/user"
      else
        redirect_to new_folder_path
      end
    end

    # The index action shows all the folders created by the user
    # The index action also handles search requests by gathering all of the
    # folders into a temp variable and then iterating across the folders
    # with a search parameter, if the name equals the search criteria
    # the @folders variable is populated and sent to index view
    def index
      @user = current_user
      if params[:search]
        @temp_folders = @user.folders
        @folders_array = []
        @temp_folders.each do |folder|
          @search = "#{params[:search]}"
          if folder.name == @search
            @folders_array.push folder
          end
        end
        @folders = @folders_array.paginate(:page => params[:page], :per_page => 2)
      else
        @folders = @user.folders.paginate(:page => params[:page], :per_page => 2)
      end
      @title = "Your Folders"
    end

    # The edit action allows users to edit their folders by changing the 
    # content or the name
    def edit
      @user = current_user
      @folder = Folder.find(params[:id])
    end

    # The update action updates the current folder in the database
    def update
      @folder = Folder.find(params[:id])
      if @folder.update_attributes(params[:folder])
        flash[:notice] = "Folder Updated!"
        redirect_to folder_path
      else
        redirect_to folders_path
      end
    end
    
    def destroy
      @folder = Folder.find(params[:id])
      @folder.destroy
      flash[:success] = "Folder deleted."
      redirect_to "/user"
    end
    
    def show
      @user = current_user
      @folder = Folder.find(params[:id])
    end
      
  end
  

app/controllers/user_controller.rb
class UserController < ApplicationController
  before_filter :authenticate_user!
  # The Users Controller handles all of the page requests for Users
  
  def show
    @user = current_user
    @folder = Folder.new
    @folders = @user.folders.paginate(:page => params[:page], :per_page => 3)
    @title = current_user.name
  end
  
  def index
    @user = current_user
    @folders = (@user.folders).sort!{|t1, t2| t1.name <=> t2.name}
    @title = current_user.name
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # Sets base title
  def title
    base_title = "Briefspace"
    if @title.nil?
      base_title
    else
      "#{base_title} | #{@title}"
    end
  end
  
  # Button definitions for links in header
  def edit_button
    edit_button = image_tag("edit_button.png", :alt => "Edit Profile")
  end
  
  def out_button
    out_button = image_tag("out_button.png", :alt => "Sign Out")
  end
  
  def new_button
    new_button = image_tag("new_button.png", :alt => "Create New Folder")
  end
  
  def profile_button
    profile_button = image_tag("profile_button.png", :alt => "Your Profile")
  end
  
  def folders_button
    folders_button = image_tag("folders_button.png", :alt => "View Folders")
  end
  
  # Gravatar image accessible by all users to attach an image to their email
  def gravatar_for(current_user, options = { :size => 30 })
    gravatar_image_tag(current_user.email.downcase, :alt => current_user.email,
                                                    :class => 'gravatar',
                                                    :gravatar => options)
  end
end

app/views/folders/edit.html.erb
<%= render 'shared/user_header' %>
	<table class="main">
		<tr>
			<td><%= render 'shared/sidebar' %></td>
			<td>
				<div class="signin round">
					<%= form_for @folder do |f| %>
						<%= render 'shared/error_messages', :object => f.object %>
						<div class="field">
							<p><%= f.label :name %><br />
							<%= f.text_field :name %></p>
							<p><%= f.label :content %><br />
							<%= f.text_area :content %></p>
							<p><%= f.label :notes %><br />
							<%= f.text_area :notes %></p><br />
						</div>
					<div class="actions">
						<%= f.submit "Submit" %>
					</div>
					<% end %>
				</div>
			</td>
		</tr>
	</table>

app/views/folders/index.html.erb
<%= render 'shared/user_header' %>
<table class="main">
	<tr>
		<td><%= render 'shared/sidebar' %></td>
		<td><%= render 'shared/main_folders' %></td>
	</tr>
</table>

app/views/folders/new.html.erb
<%= render 'shared/user_header' %>
	<table class="main">
		<tr>
			<td><%= render 'shared/sidebar' %></td>
			<td>
				<div class="signin round">
				<h2>New Folder</h2><br />
				<%= form_for @folder do |f| %>
					<%= render 'shared/error_messages', :object => f.object %>
					<div class="field">
						<p><%= f.label :name %><br />
						<%= f.text_field :name %></p>
						<p><%= f.label :content %><br />
						<%= f.text_area :content %></p>
						<p><%= f.label :notes %><br />
						<%= f.text_area :notes %></p><br />
					</div>
					<div class="actions">
						<%= f.submit "Submit" %>
					</div>
				<% end %>
				</div>
			</td>
		</tr>
	</table>

app/views/folders/show.html.erb
<%= render 'shared/user_header' %>
	<table class="main">
		<tr>
			<td><%= render 'shared/sidebar' %></td>
			<td>
				<div class="folders round">
<table class="folders">
	<tr>
		<td>
			<ul>	
				<li><%= image_tag("folder_image.png", :alt => "folder image") %>
					<strong><%= @folder.name %></strong></li>
				<li><i>Created <%= (@folder.created_at.to_formatted_s(
							:long_ordinal)).gsub! /\d\d\:\d\d/, '' %></i></li><br />
				<li><% @content = @folder.content %>
					<% @content_arr = @content.split("\r\n") %>
					<% @content_arr.each do |line| %>
					<%= link_to "#{line}", "#{line}" %><br />
					<% end %></li><br />
				<li><i>Notes:</i></li><br />
				<li><%= @folder.notes %></li><br />
				<% if user_signed_in? %>
				<li><i><%= link_to "Edit", "#{@folder.id}/edit" %>
				or&nbsp;<%= link_to "Delete", @folder, 
									:method => :delete,
	 								:confirm => "Are you sure?", 
									:title => 
									"Delete #{@folder.name}" %></i></li><br />
				<% end %>
			</ul>
		</td>
	</tr>
</table>
				</div>
			</td>
		</tr>
	</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
  		<title><%= title %></title>
		<%= csrf_meta_tag %>
		<!--[if lt IE 9]>
		<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"</script>
		<![endif]-->
  		<%= stylesheet_link_tag 'application', :media => 'screen' %>
  		<%= javascript_include_tag :defaults %>
		<link rel="shortcut icon" href="/images/favicon.ico">
  	</head>
	<body>
		<%= yield %>
		<div class="footer">
			<%= render 'shared/footer' %>
		</div>
	</body>
</html>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<h2><%= pluralize(object.errors.count, "error") %>
			prohibited this <%= object.class.to_s.underscore.humanize.downcase %> 
			from being saved:</h2>
		<p>There were problems with the following fields:</p>
		<ul>
		<% object.errors.full_messages.each do |msg| %>
			<li><%= msg %></li>
		<% end %>
		</ul>
	</div>
<% end %>

app/views/shared/_folders.html.erb
<% @folders.each do |folder| %>
<tr>
	<td>
		<ul>	
			<li><%= image_tag("folder_image.png", :alt => "folder image") %>
				<strong><%= folder.name %></strong></li>
			<li><i>Created <%= (folder.created_at.to_formatted_s(
						:long_ordinal)).gsub! /\d\d\:\d\d/, '' %></i></li><br />
			<li><% @content = folder.content %>
				<% @content_arr = @content.split("\r\n") %>
				<% @content_arr.each do |line| %>
				<%= link_to "#{line}", "#{line}" %><br />
				<% end %></li><br />
			<li><i>Notes:</i></li><br />
			<li><%= folder.notes %></li><br />
			<% if user_signed_in? %>
			<li><i><%= link_to "Edit", "folders/#{folder.id}/edit" %>
			or&nbsp;<%= link_to "Delete", folder, 
								:method => :delete,
 								:confirm => "Are you sure?", 
								:title => "Delete #{folder.name}" %></i></li><br />
			<% end %>
		</ul>
	</td>
</tr>
<% end %>

app/views/shared/_footer.html.erb
<footer>
	<p><strong>&#169 2011 Technology by Design Development</strong></p>
</footer>

app/views/shared/_main_folders.html.erb
<div class="folders round">
	<% if @folders.empty? %>
		<h4>You have no folders!
			<%= link_to "Create New Folder", new_folder_path %></h4>
	<% else %>
		<%= image_tag("folders.png", :alt => "Current Folders") %>
		<table class="folders">
			<%= render 'shared/folders' %>
		</table>
	<% end %>
	<div class="paginate">
		<%= will_paginate %>
	</div>
</div>

app/views/shared/_profile_table.html.erb
<table class="profile_list">
	<tr>
		<td>
			<p><strong>Name:</strong></p>
		</td>
		<td>
			<%= @user.name %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>Email:</strong></p>
		</td>
		<td>
			<%= @user.email %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>Company:</strong></p>
		</td>
		<td>
			<%= @user.company %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>Occupation:</strong></p>
		</td>
		<td>
			<%= @user.occupation %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>Location</strong></p>
		</td>
		<td>
			<%= @user.location %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>First Sign In:</strong></p>
		</td>
		<td>
			<%= (@user.created_at.to_formatted_s(:long_ordinal)).gsub! /\d\d\:\d\d/, '' %>
		</td>
	</tr>
	<tr>
		<td>
			<p><strong>Last Sign In:</strong></p>
		</td>
		<td>
			<%= (@user.last_sign_in_at.to_formatted_s(:long_ordinal)).gsub! /\d\d\:\d\d/, '' %>
		</td>
	</tr>
</table>

app/views/shared/_sidebar.html.erb
<div class="sidebar">
	<div class="gravatar"><%= gravatar_for @user, :size => 75 %></div>
	<h2><%= @user.name %></h2>
	<ul>
		<li><%= link_to folders_button, folders_path %></li>
		<li><%= link_to profile_button, user_index_path %></li>
		<li><%= link_to new_button, new_folder_path %></li>
		<li><%= link_to edit_button, edit_user_registration_path %></li>
		<li><%= link_to out_button, destroy_user_session_path %></li>
	</ul>
</div>

app/views/shared/_user_header.html.erb
<div class="header">
	<%= image_tag('header.png', :alt => "header") %>
	<div class="search">
		<%= form_tag folders_path, :method => 'get' do %>
		<%= text_field_tag(:search, params[:search], 
							:size => 50) %>
			<%= submit_tag "Search", :name => nil %>
			<% end %>
	</div>
</div>

app/views/shared/_user_main.erb
<div class="folders round">
	<h1><%= image_tag('welcome_logo.png', :alt => "Welcome to Briefspace") %></h1>
	<table class="usermain">
		<tr>
			<td>
				<h2><b>Your current folders:</b></h2><br />
				<% if @user.folders.empty? %>
				<p>You have no folders!</p>  
				<p>Create your first folder by clicking
					<%= link_to "New Folder", new_folder_path %></p>
				<% else %>
				<% @folders.each do |folder| %>
					<ul>
						<li><%= link_to "#{folder.name}", "/folders/#{folder.id}" %></li>
					</ul>
				<% end %>
				<% end %>
			</td>
			<td>
				<h2><b>Your profile:</b></h2><br />
				<%= render 'shared/profile_table' %>
			</td>
		</tr>
	</table>
	<div class="gravinfo">
		<h2><b>Gravatar Information</b></h2>
		<p>Would you like to add or change your profile picture?  Gravatar is an 	
			easy and efficient way to manage profile pictures across member 	 
			websites.  Just visit <%= link_to "gravatar.com", 
			"http://gravatar.com" %>.</p>
	</div>
</div>

app/views/user/index.html.erb
<%= render 'shared/user_header' %>
	<table class="main">
		<tr>
			<td><%= render 'shared/sidebar' %></td>
			<td><%= render 'shared/user_main' %></td>
		</tr>
	</table>

app/views/user/show.html.erb
<h2>This is the User home page</h2>